packages:
  - 'apps/*'
  - 'packages/*'
  - '!**/test/**'

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
  tailwind:
    tailwindcss: '^4.0.6'
    tailwind-merge: '^3.0.1'
    tailwindcss-animate: '^1.0.7'
    '@tailwindcss/postcss': '^4.0.6'
